# .gitlab-ci.yml file

image: node:latest
cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - .npm/

stages:
  - validate
  - test
  - build
  - release
  - deploy

.default_test_stage: &default_test_stage
  <<: *default_test_stage
  stage: test


install:
  stage: .pre
  script:
    # define cache dir & use it npm!
    - npm ci --cache .npm --prefer-offline

lint:
  stage: validate
  script:
    - npm run lint
  rules:
    - if: '$CI_COMMIT_TAG == null
        && $CI_COMMIT_TITLE !~ /^chore: release/'

unit-test:
  <<: *default_test_stage
  script:
    - npm test
  rules:
    - if: '$CI_COMMIT_TAG == null
        && $CI_COMMIT_TITLE !~ /^chore: release/'   

E2E_test:
  <<: *default_test_stage
  script: 
    - echo "HEllo E2E !"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" 

release:
  stage: release
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"
        && $CI_COMMIT_TAG == null
        && $CI_COMMIT_TITLE !~ /^chore: release/'
  before_script:
    - git config user.email $GITLAB_USER_EMAIL
    - git config user.name $GITLAB_USER_NAME
    - git remote set-url origin
      "https://gitlab-ci-token:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    - git checkout $CI_COMMIT_BRANCH
    - git pull origin $CI_COMMIT_BRANCH --rebase
  script:
    - npx --yes release-it --ci
